import { Inter } from 'next/font/google'
// import global css
import '@/app/styles/globals.css'
import { QueryParamsProvider } from '@/contexts/queryParamsContext';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Stay Nest',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <QueryParamsProvider>
        {children}
        </QueryParamsProvider>
      </body>
    </html>
  )
}
